# Generated by Django 4.1.4 on 2023-01-09 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_profile_description_profile_insta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='github',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
    ]
