# Generated by Django 4.1.4 on 2023-01-06 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_order_quantity_alter_order_payment_method'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='item',
            new_name='good',
        ),
    ]
