# Generated by Django 4.1.4 on 2023-01-16 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_goods_category_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='sale',
            field=models.BooleanField(default=False),
        ),
    ]
