# Generated by Django 4.1.4 on 2023-01-26 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_goods_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='pay_method',
            field=models.CharField(choices=[('visa', 'visa'), ('cash', 'cash')], max_length=10),
        ),
    ]
